### ISSUE TITLE
IndexOfNewlineChar optimization?

### ISSUE THREAD

**Issue by richardtallent** [praeclarum/1brc#1]
Not entirely sure I'm following your code (I can't find where the powers of 10 are actually *used*, for example).

But something struck me about `IndexOfNewlineChar`: if only `\r\n` and `\n` variants are supported (not the `\r`-only variant that is a relic of old Macs), you can look *only* for `\n`, and if found and `idx` > 0, *then* go see if it is preceeded by `\r` and thus needs a 2-character stride. Something like:

```C#
internal static int IndexOfNewlineChar(ReadOnlySpan<byte> span, out int stride)
 {
    stride = default;
    int idx = span.IndexOf((byte)'\n');
    if (idx < 0) return;
    int lastIdx = idx - 1;
    if (idx > 0 && span[lastIdx] == '\r') {
       stride = 2;
       return lastIdx;
    }
    stride = 1;
    return idx;
}
```

**Comment by praeclarum** [comment]
Hey @richardtallent I think you want to post those over on @buybackoff's repo.

**Comment by richardtallent** [comment]
Whoops! You are correct, thanks! Had both open in tabs...
