### ISSUE TITLE
How to register?

### ISSUE THREAD

**Issue by bbronisz** [praeclarum/1brc#2]
Hi,

there is no information how to register new entries or if there's a deadline.
I would like to add mine https://github.com/bbronisz/1brc to see how it performs on the mac which I cannot test, cause I don't have one :).
I've implemented it to only work with unix newlines, cause I've used the original Java generator to create measurements file.

Best regards,
Beniamin.

**Comment by praeclarum** [comment]
Hello! You scored 6.55 seconds on my machine. Nice! https://github.com/praeclarum/1brc/commit/9d20d428ac0d39bceaf8450a8da095c512eddec2

**Comment by bbronisz** [comment]
@praeclarum I've updated my implementation. Could you check it on your machine?
